---
# tasks file for neutron-compute
- name: Achieve admin data from host
  shell: |
      ifconfig |grep -B1 "{{admin_segment}}"|sed "s#inet##g"|tr -d " "|awk -F":|net" '{print $1}'
  register: results

- name: set admin ip and admin device
  set_fact:
    admin_ip: "{{results.stdout_lines[1]}}"
    admin_device: "{{results.stdout_lines[0]}}"

- name: Achieve public data from host
  shell: |
      ifconfig |grep -B1 "{{public_segment}}"|sed "s#inet##g"|tr -d " "|awk -F":|net" '{print $1}'
  register: results

- name: set public ip and public device
  set_fact:
    public_ip: "{{results.stdout_lines[1]}}"
    public_device: "{{results.stdout_lines[0]}}"

- name: Achieve storage data from host
  shell: |
      ifconfig |grep -B1 "{{public_segment}}"|sed "s#inet##g"|tr -d " "|awk -F":|net" '{print $1}'
  register: results

- name: set storage ip and storage device
  set_fact:
    storage_ip: "{{results.stdout_lines[1]}}"
    storage_device: "{{results.stdout_lines[0]}}"
- name: Install nova-compute
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - openstack-neutron-openvswitch
    - ebtables 
    - ipset

- name: Create Keystone config shell script
  template:
    src: openstack_config_neutron_compute.sh.j2
    dest: /tmp/openstack_config_neutron_compute.sh
    mode: '700'
    backup: yes

- name: Execute keystone shell script
  shell: |
    /bin/bash /tmp/openstack_config_neutron_compute.sh


- name: sysctl alter
  sysctl:
    name: "{{item}}"
    value: 1
    sysctl_file: /etc/sysctl.d/bridge_filters.conf
    sysctl_set: yes
    ignoreerrors: yes
  with_items:
    - "net.bridge.bridge-nf-call-iptables"
    - "net.bridge.bridge-nf-call-ip6tables"

- name: restart 
  systemd:
    name: openstack-nova-compute.service
    state: restarted 

- name: Enable and start neutron-openvswitch-agent.service
  systemd:
    name:  neutron-openvswitch-agent.service
    enabled: yes
    state: started
