---
# vars file for cinder-server
- name: Achieve admin data from host
  shell: |
      ifconfig |grep -B1 "{{admin_segment}}"|sed "s#inet##g"|tr -d " "|awk -F":|net" '{print $1}'
  register: results

- name: set admin ip and admin device
  set_fact:
    admin_ip: "{{results.stdout_lines[1]}}"
    admin_device: "{{results.stdout_lines[0]}}"

- name: Achieve public data from host
  shell: |
      ifconfig |grep -B1 "{{public_segment}}"|sed "s#inet##g"|tr -d " "|awk -F":|net" '{print $1}'
  register: results

- name: set public ip and public device
  set_fact:
    public_ip: "{{results.stdout_lines[1]}}"
    public_device: "{{results.stdout_lines[0]}}"

- name: Achieve storage data from host
  shell: |
      ifconfig |grep -B1 "{{public_segment}}"|sed "s#inet##g"|tr -d " "|awk -F":|net" '{print $1}'
  register: results

- name: set storage ip and storage device
  set_fact:
    storage_ip: "{{results.stdout_lines[1]}}"
    storage_device: "{{results.stdout_lines[0]}}"

- name: Install cinder
  yum:  
    name: openstack-cinder
    state: installed

- name: Create a new database with name "{{ database_name }}" 
  mysql_db:
    login_host: "{{admin_vip}}"
    login_user: "root"
    login_password: "{{ mysql_password }}"
    name: "{{ database_name }}"
    state: present
  when: master == 1

- name:  Create a new user with name "{{ user_name }}" 
  mysql_user:
    login_host: "{{admin_vip}}"
    login_user: "root"
    login_password: "{{mysql_password }}"
    name: "cinder"
    priv: "cinder.*:ALL"
    host: "{{ item }}"
    password: "{{ user_password }}"
    state: present
  with_items:
    - "{{user_privilege}}"
  when: master == 1

- name: Add User
  shell: |
    . ~/admin-openrc
    openstack user create --domain "{{item.domain}}" --password "{{item.password}}" "{{item.name}}" 
  with_items:
    - "{{user}}"
  ignore_errors: yes
  when: master == 1


- name: relevance project and user role
  shell: |
     . ~/admin-openrc
     openstack role add --project "{{item.project}}" --user "{{item.user}}"  "{{item.role}}" 
  with_items:
    - "{{bind}}"
  ignore_errors: yes
  when: master == 1


- name: Create service
  shell: |
    . ~/admin-openrc
    openstack service create --name "{{item.name}}" --description "{{item.description}}" "{{item.contend}}" 
  with_items:
    - "{{create_service}}"
  when: master == 1
  ignore_errors: yes

- name: Create endpoint
  shell: |
    . ~/admin-openrc
    openstack endpoint create --region RegionOne "{{item.0.name}}" "{{item.1}}" "{{item.0.url}}" 
  with_cartesian:
    - "{{endpoint}}"
    - "{{zone}}"
  ignore_errors: yes
  when: master == 1

- name: Create cinder-server config shell script
  template:
    src: openstack_config_cinder_server.sh.j2
    dest: /tmp/openstack_config_cinder_server.sh
    mode: '700'
    backup: yes

- name: Execute keystone shell script
  shell: |
    /bin/bash /tmp/openstack_config_cinder_server.sh

- name: Sync Database
  shell: |
     su -s /bin/sh -c "cinder-manage db sync" cinder
  when: master == 1

- name: restart openstack-nova-api.service
  systemd:
    name: openstack-nova-api.service
    state: restarted

- name: Start cinder
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
    - openstack-cinder-api.service 
    - openstack-cinder-scheduler.service
