---
# tasks file for etcd
- name: Achieve data from host
  shell: |
      ifconfig |grep -B1 "{{admin_segment}}"|sed "s#inet##g"|tr -d " "|awk -F":|net" '{print $1}'
  register: results

- name: set admin ip and admin device
  set_fact:
    admin_ip: "{{results.stdout_lines[1]}}"
    admin_device: "{{results.stdout_lines[0]}}"

- name: Achieve  data from host
  shell: |
      ifconfig |grep -B1 "{{public_segment}}"|sed "s#inet##g"|tr -d " "|awk -F":|net" '{print $1}'
  register: results

- name: set public ip and public device
  set_fact:
    public_ip: "{{results.stdout_lines[1]}}"
    public_device: "{{results.stdout_lines[0]}}"

- name: Install etcd
  yum:
    name: etcd
    state: installed

- name: Config etcd
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    backup: yes

- name: Enable etcd
  systemd:
    state: started
    name: etcd
    enabled: yes
