---
# tasks file for memcached
- name: Achieve data from host
  shell: |
      ifconfig |grep -B1 "{{admin_segment}}"|sed "s#inet##g"|tr -d " "|awk -F":|net" '{print $1}'
  register: results

- name: set admin ip and admin device
  set_fact:
    admin_ip: "{{results.stdout_lines[1]}}"
    admin_device: "{{results.stdout_lines[0]}}"
- name: Install Memcached
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - memcached 
    - python-memcached
 
- name: Config Memcached
  template:
    src: memcached.j2
    dest: /etc/sysconfig/memcached
    backup: yes


- name: Start memcached
  service:
    name: memcached.service
    state: started

- name: Enable memcached
  systemd:
    name: memcached
    enabled: yes



